name: Build guides

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  import:
    name: Import the guides
    runs-on: ubuntu-latest
    steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - name: Configure git
      run: |
        git config --global user.name "Automation"
        git config --global user.email "automation@osbuild.org"
    - name: Clone local repository
      uses: actions/checkout@v3
      with:
        path: sources
    - name: Clone local repository
      uses: actions/checkout@v3
      with:
        path: rendered
        ref: gh-pages
    - run: ls -la; ls -la sources; ls -la rendered
    - name: Render Image Builder guide
      working-directory: sources
      run: |
        mdbook build -d ../../rendered/docs/
    - name: Publish the rendered guide
      if: ${{ github.ref == 'refs/heads/main' }}
      working-directory: rendered
      run: |
        pwd
        ls -la
        git add .
        git commit -m "Render website" || echo "No changes"
        git push origin gh-pages
    - name: upload build result
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: actions/upload-artifact@v3
      with:
        name: build result
        path: ./rendered/docs/
